"""Baseline for existing schema.

This is an empty migration that exists only to anchor Alembic's history
to the current production database state. Existing environments should
run:

    alembic stamp 8f92617d07be

after installing Alembic, to record their DB as already at this
revision. Fresh databases should run `init_db()` (models.Base.metadata
.create_all) once and then `alembic stamp head`.

All schema changes from this point forward go through autogenerated
revisions (`alembic revision --autogenerate -m "..."`).

Revision ID: 8f92617d07be
Revises:
Create Date: 2026-04-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f92617d07be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
